---
title: "Table 1"
output: word_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r hello}
#loading libraries
library(gtsummary)
library(tidyverse)

```


```{r sgp set up}

BRFSS <- read.csv("/Users/aileenandrade/Desktop/Spring Quarter/Epi 514/BRFSS project/Data/cleanbrfss.csv")
```

```{r}

BRFSS <- read.csv("/Users/aileenandrade/Desktop/Spring Quarter/Epi 514/BRFSS project/Data/cleanbrfss.csv") 
```


```{r table}


theme_gtsummary_journal(journal = "jama")
#Setting theme `JAMA` 



#Setting theme `Compact`
theme_gtsummary_compact(font_size = 10)

table1 <- BRFSS %>%
  select( "CervScrnEver.f", "HlthDiscrim.f","RaceOthers.f", "income.f", 
         "employ.f", "insurance.f", "edu.f", "age.f", "GenHlth.f") %>%
  tbl_summary(by = "CervScrnEver.f", 
              missing = "always", 
              type = list(
                HlthDiscrim.f ~"categorical", 
                RaceOthers.f  ~ "categorical",
                income.f ~ "categorical",
                employ.f ~ "categorical",
                insurance.f ~ "categorical",
                edu.f ~ "categorical",
                age.f ~ "categorical", 
                GenHlth.f ~ "categorical"),
              statistic = all_continuous() ~ "{mean} ({sd})",
              digits = list(all_continuous() ~ 1,
                            all_categorical() ~ c(0, 1)), 
              label = list(
                HlthDiscrim.f ~ "Perceived Discrimination", 
                RaceOthers.f  ~ "Race and Ethnicity",
                income.f ~ "Annual Household Income",
                employ.f ~ "Employed",
                insurance.f ~ "Health Coverage",
                edu.f ~ "Education Status",
                age.f~ "Age (years)", 
                GenHlth.f ~ "Health Status", 
                na_suffix = " (NA %) "
              )) %>% 
  add_overall() %>%
                   modify_header(label = "**Variable**") %>%
                   modify_spanning_header(list(stat_1 ~ "**Cervical Cancer Screening**",
                                               stat_2 ~ "**Cervical Cancer Screening**"
                                               )) 
  


print(table1)


```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
